r"""
CapyMorph — character morph (your OWN character only), via a generated addon.

A client-side MPQ patch cannot target one character (all e.g. Human Females
share a model). Instead we use the TurtleWoW client extension VanillaHelpers,
whose Lua API works per-unit and locally (no server effect, others unaffected):

    SetUnitDisplayID("player" [, displayID])      whole-body model (or reset)
    SetUnitVisibleItemID("player", slot [, item])  per-slot item appearance
    UnitDisplayInfo("player")                      read current display

The user's per-character config (data/char_morph.json):
    { "model": <displayID|null>,
      "items": [ {slot, item_id, label} ],   # slot = equipment inventory slot
      "unform": [ {form, label, displays:[...]} ] }  # forms to show char instead

We generate Interface\AddOns\CapyMorph from it; the addon re-applies on
login and on a short timer, plus /cm to re-apply manually.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from typing import Optional

import tm_config as cfg


def _res(name: str) -> str:
    """Locate a bundled .lua template (works both from source and frozen exe)."""
    base = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    p = os.path.join(base, name)
    if os.path.exists(p):
        return p
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), name)

ADDON_NAME = "CapyMorph"
ADDONS_DIR = os.path.join(cfg.CLIENT_ROOT, "Interface", "AddOns")
ADDON_DIR = os.path.join(ADDONS_DIR, ADDON_NAME)
CONFIG_PATH = os.path.join(cfg.DATA_DIR, "char_morph.json")
DATA_GLOBAL = "CapyMorphData"

# inventory_type (item_template) -> equipment inventory slot (for SetUnitVisibleItemID)
INVTYPE_TO_SLOT = {
    1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 20: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10,
    11: 11, 12: 13, 16: 15, 19: 19,
    13: 16, 21: 16, 17: 16,        # weapons -> main hand
    22: 17, 14: 17, 23: 17,        # off hand / shield / held
    15: 18, 26: 18, 25: 18,        # ranged
}

_TOC = """## Interface: 11200
## Title: CapyMorph
## Version: 1.0.0
## Notes: Locally morphs your own character (VanillaHelpers) — in-game UI + /cm
## SavedVariablesPerCharacter: CapyMorphDB
CapyMorphData.lua
CapyMorph.lua
CapyMorphUI.lua
"""


def default_config() -> dict:
    # model  : whole-body creature display (always on)
    # items  : per-slot item look [{slot, item_id, label}]
    # forms  : per-character form override [{form, displays:[...], target, label}]
    # unform : suppress a form -> show character [{form, displays:[...], label}]
    return {"model": None, "items": [], "forms": [], "unform": [], "_form_displays": {}}


def load_config() -> dict:
    if os.path.exists(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                c = json.load(f)
            for k, v in default_config().items():
                c.setdefault(k, v)
            return c
        except Exception:
            pass
    return default_config()


def save_config(c: dict):
    cfg.ensure_dirs()
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(c, f, ensure_ascii=False, indent=1)


def _lua(config: dict) -> str:
    model = config.get("model")
    items = config.get("items", [])
    unform_displays = sorted({d for u in config.get("unform", []) for d in u.get("displays", [])})
    # form override: display -> target
    formmap = {}
    for fo in config.get("forms", []):
        for d in fo.get("displays", []):
            if fo.get("target"):
                formmap[d] = fo["target"]
    fdisp = config.get("_form_displays", {})  # {bear:[...], cat:[...], moonkin:[...]} for /cm form

    items_lua = ", ".join(f"{{{it['slot']},{it['item_id']}}}" for it in items if it.get("item_id"))
    unform_lua = ", ".join(f"[{d}]=1" for d in unform_displays)
    formmap_lua = ", ".join(f"[{d}]={t}" for d, t in sorted(formmap.items()))
    forms_lua = ", ".join(
        f'["{name.split()[0].lower()}"]={{{", ".join(str(d) for d in ds)}}}'
        for name, ds in fdisp.items())

    header = (
        "-- Generated by CapyMorph. Affects ONLY your character, locally.\n"
        f"local DEF_MODEL = {model if model else 'nil'}\n"
        f"local DEF_ITEMS = {{{items_lua}}}\n"
        f"local DEF_UNFORM = {{{unform_lua}}}\n"
        f"local DEF_FORMMAP = {{{formmap_lua}}}\n"
        f"local FORMS = {{{forms_lua}}}\n\n"
    )
    with open(_res("_addon_main.lua"), "r", encoding="utf-8") as fh:
        return header + fh.read()


def write_addon(config: dict) -> str:
    """Generate the addon (TOC + data-aware main + UI). Returns the addon dir."""
    os.makedirs(ADDON_DIR, exist_ok=True)
    with open(os.path.join(ADDON_DIR, ADDON_NAME + ".toc"), "w", encoding="utf-8") as f:
        f.write(_TOC)
    with open(os.path.join(ADDON_DIR, ADDON_NAME + ".lua"), "w", encoding="utf-8") as f:
        f.write(_lua(config))
    # static UI
    with open(_res("_addon_ui.lua"), "r", encoding="utf-8") as fh:
        ui = fh.read()
    with open(os.path.join(ADDON_DIR, ADDON_NAME + "UI.lua"), "w", encoding="utf-8") as f:
        f.write(ui)
    # ensure a data file exists (empty stub if not generated yet)
    data_path = os.path.join(ADDON_DIR, ADDON_NAME + "Data.lua")
    if not os.path.exists(data_path):
        with open(data_path, "w", encoding="utf-8") as f:
            f.write(DATA_GLOBAL + " = { items = {}, creatures = {} }\n")
    return ADDON_DIR


def write_data(items_by_slot: dict, creatures: list) -> str:
    """
    Generate CapyMorphData.lua for the in-game UI search lists.
      items_by_slot: { inventorySlot(int): [(name, itemID), ...] }
      creatures:     [ (name, displayID, modelPath), ... ]
    """
    os.makedirs(ADDON_DIR, exist_ok=True)

    def esc(s):
        return str(s).replace("\\", "\\\\").replace('"', '\\"')

    lines = [DATA_GLOBAL + " = { items = {}, creatures = {} }",
             "local I = " + DATA_GLOBAL + ".items", "local C = " + DATA_GLOBAL + ".creatures"]
    for slot in sorted(items_by_slot):
        entries = items_by_slot[slot]
        lines.append(f"I[{slot}] = {{")
        for name, iid in entries:
            lines.append(f'{{"{esc(name)}",{iid}}},')
        lines.append("}")
    lines.append("local n = 0")
    for name, did, path in creatures:
        lines.append(f'n=n+1; C[n]={{"{esc(name)}",{did},"{esc(path)}"}}')
    data = "\n".join(lines) + "\n"
    with open(os.path.join(ADDON_DIR, ADDON_NAME + "Data.lua"), "w", encoding="utf-8") as f:
        f.write(data)
    return ADDON_DIR


def apply_config(config: dict) -> str:
    """Persist the config and (re)generate the addon."""
    save_config(config)
    return write_addon(config)


def uninstall() -> bool:
    save_config(default_config())
    if os.path.isdir(ADDON_DIR):
        shutil.rmtree(ADDON_DIR)
        return True
    return False


def helper_present() -> bool:
    return os.path.exists(os.path.join(cfg.CLIENT_ROOT, "VanillaHelpers.dll"))


# backward-compat: simple whole-body install used by older callers
def install(display_id: int) -> str:
    c = load_config()
    c["model"] = int(display_id)
    return apply_config(c)


def installed_display() -> Optional[int]:
    return load_config().get("model")
